---
- hosts: aws_ec2
  users: ec2-user
  become: yes
  connection: ssh
  vars:
    ansible_ssh_privet_key_file: "/etc/ansible/NAGA.pem"
    ansible_ssh_user: "ec2-user"
  tasks:
    - name: installing git
      action: yum name=git state=present

    - name: installing webserver
      action: yum name=httpd state=present

    - name: restarted httpd
      service: name=httpd state=restarted
    - name: getting code to the server
      git:
        repo: "https://github.com/NAGA-087/pawar.git"
        dest: /var/www/htl/
        version: "frontend"
